/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels.System;

import Control.ProyectHandler;
import Model.Imp.RgsImp;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luisf
 */
public final class Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        try {
            db = new RgsImp();
            initComponents();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        infoPrincipal = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        ced = new javax.swing.JTextField();
        startDay = new javax.swing.JComboBox<>();
        finalDay = new javax.swing.JComboBox<>();
        hhI = new javax.swing.JComboBox<>();
        mmI = new javax.swing.JComboBox<>();
        aI = new javax.swing.JComboBox<>();
        hhF = new javax.swing.JComboBox<>();
        mmF = new javax.swing.JComboBox<>();
        aF = new javax.swing.JComboBox<>();
        on = new javax.swing.JRadioButton();
        specialDay = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        j9 = new javax.swing.JLabel();
        j10 = new javax.swing.JLabel();
        j11 = new javax.swing.JLabel();
        j12 = new javax.swing.JLabel();
        j13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();
        impr = new javax.swing.JTextField();
        hhIE = new javax.swing.JComboBox<>();
        mmIE = new javax.swing.JComboBox<>();
        aIE = new javax.swing.JComboBox<>();
        hhFE = new javax.swing.JComboBox<>();
        mmFE = new javax.swing.JComboBox<>();
        aFE = new javax.swing.JComboBox<>();
        j21 = new javax.swing.JLabel();
        telef = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        infoParqueo = new javax.swing.JPanel();
        carro = new javax.swing.JPanel();
        carCT = new javax.swing.JSpinner();
        carDCT = new javax.swing.JSpinner();
        car30 = new javax.swing.JFormattedTextField();
        car1 = new javax.swing.JFormattedTextField();
        j14 = new javax.swing.JLabel();
        j15 = new javax.swing.JLabel();
        j16 = new javax.swing.JLabel();
        j17 = new javax.swing.JLabel();
        moto = new javax.swing.JPanel();
        List<String> list =  db.findValues("CAMPOS");
        List<String> list2 = db.findValues("VALOR");

        motCT = new javax.swing.JSpinner();
        mot30 = new javax.swing.JFormattedTextField();
        mot1 = new javax.swing.JFormattedTextField();
        j18 = new javax.swing.JLabel();
        j19 = new javax.swing.JLabel();
        j20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        save2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        money = new javax.swing.JFormattedTextField();
        save3 = new javax.swing.JButton();
        msg3 = new javax.swing.JLabel();
        closure = new javax.swing.JButton();
        stats = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        infoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        infoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setText(db.findValue("NAME")
        );
        infoPrincipal.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, 30));

        ced.setText(db.findValue("CED")
        );
        infoPrincipal.add(ced, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 210, 30));

        String[] days = db.findValue("DAYS").split(" - ");
        startDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        startDay.setSelectedItem(days[0]
        );
        infoPrincipal.add(startDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, 30));

        finalDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        finalDay.setSelectedItem(days[1]
        );
        infoPrincipal.add(finalDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, -1, 30));

        String[] hr = db.findValue("HHR").split(" a ");
        hhI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        hhI.setSelectedItem(hr[0].split(":")[0]);
        infoPrincipal.add(hhI, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, 30));

        mmI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        mmI.setSelectedItem(hr[0].split(":")[1].split(" ")[0]);
        infoPrincipal.add(mmI, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 40, 30));

        aI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a.m.", "p.m." }));
        aI.setSelectedItem(hr[0].split(":")[1].split(" ")[1]);
        infoPrincipal.add(aI, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 50, 30));

        hhF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        hhF.setSelectedItem(hr[1].split(":")[0]);
        infoPrincipal.add(hhF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, 30));

        mmF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        mmF.setSelectedItem(hr[1].split(":")[1].split(" ")[0]);
        infoPrincipal.add(mmF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 40, 30));

        aF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a.m.", "p.m." }));
        aF.setSelectedItem(hr[1].split(":")[1].split(" ")[1]);
        infoPrincipal.add(aF, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 50, 30));

        on.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        on.setSelected(Boolean.valueOf(db.findValue("ONSPC"))
        );
        on.setText("Habilitar horario especial");
        infoPrincipal.add(on, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 180, -1));

        specialDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        specialDay.setSelectedItem(db.findValue("DAYSS")
        );
        infoPrincipal.add(specialDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, -1, 30));

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setText("Guardar Cambios");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        infoPrincipal.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 200, 40));

        j1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j1.setText("Nombre del Parqueo");
        infoPrincipal.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, 29));

        j2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j2.setText("Cedúla");
        infoPrincipal.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 29));

        j3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j3.setText("Nombre Impresora");
        infoPrincipal.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 130, 29));

        j4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j4.setText("Día de Inicio:");
        infoPrincipal.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 80, 29));

        j5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j5.setText("Día de Final:");
        infoPrincipal.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 80, 29));

        j6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j6.setText("Hora de Inicio:");
        infoPrincipal.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 90, 29));

        j7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j7.setText("Hora de Final:");
        infoPrincipal.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 90, 29));

        j8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j8.setText("Día Especial:");
        infoPrincipal.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 80, 29));

        j9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j9.setText("Hora de Inicio:");
        infoPrincipal.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 90, 29));

        j10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j10.setText("Hora de Final:");
        infoPrincipal.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 90, 29));

        j11.setBackground(new java.awt.Color(204, 204, 204));
        j11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j11.setText("Horario Especial");
        j11.setOpaque(true);
        infoPrincipal.add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 500, 40));

        j12.setBackground(new java.awt.Color(204, 204, 204));
        j12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j12.setText("Infomación del Principal");
        j12.setOpaque(true);
        infoPrincipal.add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 40));

        j13.setBackground(new java.awt.Color(204, 204, 204));
        j13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j13.setText("Horario Regular");
        j13.setOpaque(true);
        infoPrincipal.add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 500, 40));
        infoPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 540, 10));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setOpaque(true);
        infoPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1040, 40));

        msg1.setBackground(new java.awt.Color(204, 204, 204));
        msg1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        msg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg1.setText("Cambios guardados exitósamente");
        msg1.setOpaque(true);
        msg1.setVisible(false);
        infoPrincipal.add(msg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 270, 40));

        impr.setText(db.findValue("PRINTER")
        );
        infoPrincipal.add(impr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 210, 30));

        String[] hre = db.findValue("HHRS").split(" a ");
        hhIE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        hhIE.setSelectedItem(hre[0].split(":")[0]);
        infoPrincipal.add(hhIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, 30));

        mmIE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        mmIE.setSelectedItem(hre[0].split(":")[1].split(" ")[0]);
        infoPrincipal.add(mmIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 40, 30));

        aIE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a.m.", "p.m." }));
        aIE.setSelectedItem(hre[0].split(":")[1].split(" ")[1]);
        infoPrincipal.add(aIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 50, 30));

        hhFE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        hhFE.setSelectedItem(hre[1].split(":")[0]);
        infoPrincipal.add(hhFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, 30));

        mmFE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        mmFE.setSelectedItem(hre[1].split(":")[1].split(" ")[0]);
        infoPrincipal.add(mmFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 40, 30));

        aFE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a.m.", "p.m." }));
        aFE.setSelectedItem(hre[1].split(":")[1].split(" ")[1]);
        infoPrincipal.add(aFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 50, 30));

        j21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j21.setText("Teléfono - Contacto");
        infoPrincipal.add(j21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 29));

        telef.setText(db.findValue("TEL")
        );
        infoPrincipal.add(telef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 10, 450));

        jTabbedPane1.addTab("Información Principal", infoPrincipal);

        infoParqueo.setBackground(new java.awt.Color(255, 255, 255));
        infoParqueo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        carro.setOpaque(false);
        carro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carCT.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(list.get(1)), 0, null,1));
        carro.add(carCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 30));

        carDCT.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(list.get(2)), 0, null, 1));
        carro.add(carDCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, 30));

        car30.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        car30.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        car30.setValue(Integer.valueOf(list2.get(2)));
        carro.add(car30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 70, 30));

        car1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        car1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        car1.setValue(Integer.valueOf(list2.get(3)));
        carro.add(car1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 30));

        j14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j14.setText("Discapacitados");
        carro.add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 30));

        j15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j15.setText("30 min:");
        carro.add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 30));

        j16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j16.setText("1 h:");
        carro.add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 50, 30));

        j17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j17.setText("Campos Totales");
        carro.add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 30));

        infoParqueo.add(carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 370));

        moto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motocicletas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        moto.setOpaque(false);
        moto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        motCT.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(list.get(0)), 0, null, 1));
        moto.add(motCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 30));

        mot30.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        mot30.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mot30.setValue(Integer.valueOf(list2.get(0)));
        moto.add(mot30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 70, 30));

        mot1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        mot1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mot1.setValue(Integer.valueOf(list2.get(1))
        );
        moto.add(mot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 70, 30));

        j18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j18.setText("Campos Totales");
        moto.add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 30));

        j19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j19.setText("30 min:");
        moto.add(j19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, 30));

        j20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j20.setText("1 h:");
        moto.add(j20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 50, 30));

        infoParqueo.add(moto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 200, 370));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        infoParqueo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 10, 490));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Infomación del Cajas");
        jLabel14.setOpaque(true);
        infoParqueo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 530, 40));

        save2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save2.setText("Guardar Cambios");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        infoParqueo.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 200, 40));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setOpaque(true);
        infoParqueo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1040, 40));

        msg2.setBackground(new java.awt.Color(204, 204, 204));
        msg2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        msg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg2.setText("Cambios guardados exitósamente");
        msg2.setOpaque(true);
        msg2.setVisible(false);
        infoParqueo.add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 220, 40));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Infomación del Parqueo");
        jLabel17.setOpaque(true);
        infoParqueo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caja", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Dinero Inicial");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, 30));

        money.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        money.setValue(Integer.valueOf(db.findValue("CASH")));
        jPanel1.add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 260, 30));

        save3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save3.setText("Guardar Cambios");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });
        jPanel1.add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 260, 30));

        msg3.setBackground(new java.awt.Color(204, 204, 204));
        msg3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        msg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg3.setText("Cambios guardados exitósamente");
        msg3.setOpaque(true);
        msg3.setVisible(false);
        jPanel1.add(msg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 260, 30));

        infoParqueo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 480, 200));

        closure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closure.setText("Cierre");
        infoParqueo.add(closure, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 150, 30));

        stats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stats.setText("Estadísticas");
        infoParqueo.add(stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Click para realizar un cierre de caja.");
        infoParqueo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Click para ver estadsticas.");
        infoParqueo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 230, 30));

        jTabbedPane1.addTab("Información de Cobros", infoParqueo);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        try {
            db.updateValue(13, String.valueOf(motCT.getValue()));
            db.updateValue(14, String.valueOf(carCT.getValue()));
            db.updateValue(15, String.valueOf(carDCT.getValue()));

            db.updateValue(16, mot30.getText().replace(",", ""));
            db.updateValue(17, mot1.getText().replace(",", ""));
            db.updateValue(18, car30.getText().replace(",", ""));
            db.updateValue(19, car1.getText().replace(",", ""));

            msg2.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_save2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            db.updateValue("NAME",
                    name.getText().length() > 41
                    ? name.getText().substring(0, 40)
                    : name.getText()
            );
            db.updateValue("CED",
                    ced.getText().length() > 41
                    ? ced.getText().substring(0, 40)
                    : ced.getText()
            );
            db.updateValue("TEL", telef.getText());
            db.updateValue(
                    "DAYS",
                    String.valueOf(startDay.getSelectedItem())
                            .concat(" - ")
                            .concat(String.valueOf(finalDay.getSelectedItem()))
            );
            db.updateValue("PRINTER", impr.getText());
            ProyectHandler.instance().setPrinter(impr.getText());
            db.updateValue(
                    "HHR",
                    String.valueOf(hhI.getSelectedItem())
                            .concat(":")
                            .concat(String.valueOf(mmI.getSelectedItem()))
                            .concat(" ")
                            .concat(String.valueOf(aI.getSelectedItem()))
                            .concat(" a ")
                            .concat(String.valueOf(hhF.getSelectedItem()))
                            .concat(":")
                            .concat(String.valueOf(mmF.getSelectedItem()))
                            .concat(" ")
                            .concat(String.valueOf(aF.getSelectedItem()))
            );

            if (on.isSelected()) {
                db.updateValue("ONSPC", "true");
                db.updateValue("DAYSS", String.valueOf(specialDay.getSelectedItem()));
                db.updateValue(
                        "HHRS",
                        String.valueOf(hhI.getSelectedItem())
                                .concat(":")
                                .concat(String.valueOf(mmIE.getSelectedItem()))
                                .concat(" ")
                                .concat(String.valueOf(aIE.getSelectedItem()))
                                .concat(" a ")
                                .concat(String.valueOf(hhFE.getSelectedItem()))
                                .concat(":")
                                .concat(String.valueOf(mmFE.getSelectedItem()))
                                .concat(" ")
                                .concat(String.valueOf(aFE.getSelectedItem()))
                );
            } else {
                db.updateValue("ONSPC", "false");
            }

            msg1.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
        try {
            db.updateValue(21, money.getText().replace(",", ""));
            msg3.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aF;
    private javax.swing.JComboBox<String> aFE;
    private javax.swing.JComboBox<String> aI;
    private javax.swing.JComboBox<String> aIE;
    private javax.swing.JFormattedTextField car1;
    private javax.swing.JFormattedTextField car30;
    private javax.swing.JSpinner carCT;
    private javax.swing.JSpinner carDCT;
    private javax.swing.JPanel carro;
    private javax.swing.JTextField ced;
    private javax.swing.JButton closure;
    private javax.swing.JComboBox<String> finalDay;
    private javax.swing.JComboBox<String> hhF;
    private javax.swing.JComboBox<String> hhFE;
    private javax.swing.JComboBox<String> hhI;
    private javax.swing.JComboBox<String> hhIE;
    private javax.swing.JTextField impr;
    private javax.swing.JPanel infoParqueo;
    private javax.swing.JPanel infoPrincipal;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j12;
    private javax.swing.JLabel j13;
    private javax.swing.JLabel j14;
    private javax.swing.JLabel j15;
    private javax.swing.JLabel j16;
    private javax.swing.JLabel j17;
    private javax.swing.JLabel j18;
    private javax.swing.JLabel j19;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j20;
    private javax.swing.JLabel j21;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> mmF;
    private javax.swing.JComboBox<String> mmFE;
    private javax.swing.JComboBox<String> mmI;
    private javax.swing.JComboBox<String> mmIE;
    private javax.swing.JFormattedTextField money;
    private javax.swing.JFormattedTextField mot1;
    private javax.swing.JFormattedTextField mot30;
    private javax.swing.JSpinner motCT;
    private javax.swing.JPanel moto;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel msg3;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton on;
    private javax.swing.JButton save;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    private javax.swing.JComboBox<String> specialDay;
    private javax.swing.JComboBox<String> startDay;
    private javax.swing.JButton stats;
    private javax.swing.JTextField telef;
    // End of variables declaration//GEN-END:variables
    private RgsImp db;
}
