/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Panels.Index;
import View.Panels.Ingresos;
import View.Panels.Registrar;
import View.Panels.Salida;
import View.Panels.TablaV;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author luis
 */
public final class Fondo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Registrar
     */
    public Fondo() {
        this.initComponents();
        this.startWindowComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parqueo");
        setMinimumSize(new java.awt.Dimension(700, 510));
        setPreferredSize(new java.awt.Dimension(700, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Menú");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 510));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 510));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 510));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_image.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 510));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 510));
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 510));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.mainPanel();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void startWindowComponents(){
        JPanel index = new Index();
        ((Index) index).setActions(this);
        index.setBounds(0, 0, 700, 510);
        this.jPanel1.add(index);
        this.jButton2.setVisible(false);
        this.setResizable(false);
        this.setVisible(true);        
        this.setLocationRelativeTo(null);    
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        String text = ((JButton) e.getSource()).getText();
        JPanel p = null;

        switch (text) {
            case "Entrada": {
                p = new Registrar();
                break;
            }
            case "Salida": {
                p = new Salida();
                break;
            }
            case "Lista Vehiculos": {
                p = new TablaV();
                break;
            }
            case "Ingresos": {
                p = new Ingresos();
                break;
            }
            default:
                return;
        }

        this.jPanel1.removeAll();
        javax.swing.JPanel j = new Registrar();
        p.setBounds(0, 0, 700, 510);
        this.jPanel1.add(p);
        this.jButton2.setVisible(true);
        this.validate();
        this.repaint();
    }

    public void mainPanel() {
        JPanel index = new Index();
        ((Index) index).setActions(this);
        index.setBounds(0, 0, 700, 510);
        this.jPanel1.removeAll();
        this.jPanel1.add(index);
        this.jButton2.setVisible(false);
        this.validate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
