DROP SCHEMA IF EXISTS PRQ;
CREATE SCHEMA IF NOT EXISTS PRQ DEFAULT CHARACTER SET UTF8 ;
USE PRQ;

-- ----------------------------------------------------------------
-- TABLAS
-- ----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS PRQ . TMP_RGS (
  MAT 	VARCHAR(10) NOT NULL,
  TP	INT NOT NULL,
  IH	DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (MAT)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRQ . RGS (
  ID	INT NOT NULL AUTO_INCREMENT,
  MAT	VARCHAR(10) NOT NULL,
  TP	INT NOT NULL,
  IH	DATETIME,
  OH 	DATETIME DEFAULT CURRENT_TIMESTAMP,
  TTL	DOUBLE NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRQ . USR (
  USR	VARCHAR(20) NOT NULL,
  PASS	VARCHAR(45) NOT NULL,
  PROF	VARCHAR(45) NULL,
  PRIMARY KEY (USR)
) ENGINE = InnoDB;

-- ----------------------------------------------------------------
-- PROCEDURES
-- ----------------------------------------------------------------

DELIMITER $$
USE PRQ $$
CREATE PROCEDURE PRQ . NEW_RGS (
	IN XMAT VARCHAR(10),
	IN XTP	INT 
)
BEGIN
	INSERT INTO PRQ . TMP_RGS (MAT, TP)  VALUES (XMAT, XTP);
END$$
DELIMITER ;

DELIMITER $$
USE PRQ $$
CREATE PROCEDURE PRQ . DEL_RGS (
	IN XMAT	VARCHAR(10),
    IN XTTL DOUBLE 
)
BEGIN	
    IF EXISTS (SELECT MAT FROM TMP_RGS WHERE TMP_RGS.MAT = XMAT LIMIT 1)
		THEN
			INSERT INTO RGS (MAT, TP, IH, TTL)
			SELECT OBJ.MAT, OBJ.TP, OBJ.IH, XTTL 
			FROM TMP_RGS OBJ
			WHERE OBJ.MAT = XMAT LIMIT 1; 
	
			DELETE FROM PRQ.TMP_RGS 
			WHERE TMP_RGS.MAT = XMAT
			LIMIT 1;
	END IF;
END$$
DELIMITER ;

DELIMITER $$
USE PRQ $$
CREATE PROCEDURE PRQ . RGS_BTW_DATES (
	IN XSTART DATE,
	IN XEND	  DATE
)
BEGIN
	SELECT 	RGS.TP, RGS.TTL
    FROM 	PQR.RGS
    WHERE 	RGS.IH BETWEEN XSTART AND XEND; 
END$$
DELIMITER ;

DELIMITER $$
USE PRQ $$
CREATE PROCEDURE PRQ . NEW_USER (
	IN XUSR	VARCHAR(20),
	IN XPAS	VARCHAR(45),
	IN XPRO	VARCHAR(45)
)
BEGIN
	INSERT INTO PRQ . USR VALUES (XUSR, XPAS, XPRO);
END$$
DELIMITER ;

DELIMITER $$
USE PRQ $$
CREATE PROCEDURE PRQ . DEL_ALL_TMP ()
BEGIN
	DECLARE CNT INT;
    SET CNT = (SELECT COUNT(*) FROM TMP_RGS);
    IF CNT > 0
		THEN
			TRUNCATE TABLE TMP_RGS;
    END IF;
    
    SELECT CNT;
END$$
DELIMITER ;

-- ----------------------------------------------------------------
-- TRIGGERS
-- ----------------------------------------------------------------

DELIMITER $$
USE PRQ $$
CREATE DEFINER = CURRENT_USER TRIGGER PRQ . USR_SET 
BEFORE INSERT ON USR FOR EACH ROW
BEGIN
	SET NEW.USR = LOWER(NEW.USR);
END$$
DELIMITER ;

-- -----------------------------------------------------
-- SCHEMA PRQ
-- -----------------------------------------------------
GRANT USAGE ON *.* TO admin;
DROP USER admin;
CREATE USER 'admin' IDENTIFIED BY 'Wireless.VQLF12';
GRANT ALL ON PRQ.* TO 'admin';

GRANT USAGE ON *.* TO user;
 DROP USER emp;
CREATE USER 'emp' IDENTIFIED BY 'emp2017';
GRANT EXECUTE ON PRQ.* TO 'emp';
GRANT SELECT ON TABLE PRQ.* TO 'emp';
