USE PRQ;

DROP SCHEMA IF EXISTS PRQ;
CREATE SCHEMA IF NOT EXISTS PRQ DEFAULT CHARACTER SET UTF8 ;
USE PRQ;

CALL IN_RGS('AAA-111',1);
CALL IN_RGS('AAA-112',1);
CALL IN_RGS('AAA-113',1);
CALL IN_RGS('AAA-114',2);
CALL IN_RGS('AAA-115',2);
CALL IN_RGS('AAA-116',2);

CALL NEW_USER('luis','aaa','Luis');
/*CALL FIND_USER('LUIS','aaa');*/
CALL RGS_OH_NULL();
CALL OUT_RGS('AAA-116',NOW(),5551);

SELECT NOW();
CALL GET_BILL();

call FIND_KEYVALUES('MAX');
CALL FIND_KEYVALUES('MAX');
CALL UPDATE_BILL('Z - 999');
select * from rgs