/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

import java.awt.event.ActionListener;

/**
 *
 * @author luisf
 */
public class Index extends javax.swing.JPanel {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Entrada = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        Lista_v = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        Lista_u = new javax.swing.JButton();
        Estadistica = new javax.swing.JButton();
        Ingresos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 510));
        setMinimumSize(new java.awt.Dimension(700, 510));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(700, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("MENÚ PRINCIPAL");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 650, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VEHICULOS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 233, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USUARIOS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 233, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRATIVO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 220, -1));

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText(" Luis Fernando Vásquez Quirós");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 10));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Teléfono:8318-4748");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Sistema Control de Parqueo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Versión 1.0");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manual de Usuario");
        jLabel8.setToolTipText("");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 410, 120, -1));

        Entrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Entrada.setText("Entrada");
        add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, -1));

        Salida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salida.setText("Salida");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, -1));

        Lista_v.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lista_v.setText("Lista Vehiculos");
        Lista_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_vActionPerformed(evt);
            }
        });
        add(Lista_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, -1));

        Nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 130, -1));

        Lista_u.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lista_u.setText("Lista");
        add(Lista_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 130, -1));

        Estadistica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Estadistica.setText("Estadística");
        add(Estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 130, -1));

        Ingresos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ingresos.setText("Ingresos");
        add(Ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 130, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 10, 380));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 10, 380));

        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 120, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidaActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Lista_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_vActionPerformed

    public void setActions(ActionListener a){
        Entrada.addActionListener(a);
        Estadistica.addActionListener(a);
        Ingresos.addActionListener(a);
        Lista_u.addActionListener(a);
        Lista_v.addActionListener(a);
        Nuevo.addActionListener(a);
        Salida.addActionListener(a);       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrada;
    private javax.swing.JButton Estadistica;
    private javax.swing.JButton Ingresos;
    private javax.swing.JButton Lista_u;
    private javax.swing.JButton Lista_v;
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton Salida;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
