/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

import BD.DB;
import Entities.Vehiculo;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luisf
 */
public class Ingresos extends javax.swing.JPanel {

    /**
     * Creates new form Ingresos
     */
    public Ingresos() {
        initComponents();
        err.setVisible(false);
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        date2 = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        err = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        mt = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        mm = new javax.swing.JLabel();
        mo = new javax.swing.JLabel();
        ma = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        t = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(700, 510));
        setMinimumSize(new java.awt.Dimension(700, 510));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(700, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Inicio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 20));
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Final");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 20));
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Muestra Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));

        err.setForeground(new java.awt.Color(255, 0, 51));
        err.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        err.setText("Fechas Incorrectas.");
        jPanel1.add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 280, 200));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Otros");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Automoviles");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Motocicletas");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 80, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 10, 140));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 10, 140));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 300, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 300, 10));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, -1));

        jLabel9.setText("Cantidad");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel10.setText("Montos");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m.setText("0");
        jPanel2.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 60, -1));

        mt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mt.setText("0");
        jPanel2.add(mt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, -1));

        a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a.setText("0");
        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 60, -1));

        mm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mm.setText("0");
        jPanel2.add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, -1));

        mo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mo.setText("0");
        jPanel2.add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 90, -1));

        ma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ma.setText("0");
        jPanel2.add(ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 90, -1));

        o.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o.setText("0");
        jPanel2.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, -1));

        t.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t.setText("0");
        jPanel2.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 420, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DB d = new DB();
            Date d1 = date1.getDate();
            Date d2 = date2.getDate();

            int ia = 0, im = 0, io = 0;
            double ima = 0, imm = 0, imo = 0;
            
            if (d1 != null && d2 != null && d2.after(d1)) {
                List<Vehiculo> lista = d.registrosFechas(new java.sql.Date(d1.getTime()), new java.sql.Date(d2.getTime()));
                for (Vehiculo v : lista) {
                    switch (v.getTipo()) {
                        case "N":
                            ia++;
                            ima += v.getTotal();
                            break;
                        case "A":
                            ia++;
                            ima += v.getTotal();
                            break;
                        case "M":
                            im++;
                            imm += v.getTotal();
                            break;
                        default:
                            io++;
                            imo += v.getTotal();
                            break;
                    }
                }
                this.a.setText(Integer.toString(ia));
                this.m.setText(Integer.toString(im));
                this.o.setText(Integer.toString(io));
                
                this.ma.setText(Double.toString(ima));
                this.mm.setText(Double.toString(imm));
                this.mo.setText(Double.toString(imo));
                
                this.t.setText(Integer.toString(ia + im + io));
                this.mt.setText(Double.toString(ima + imm + imo));
                
                err.setVisible(false);
                jPanel2.setVisible(true);
            } else {
                err.setVisible(true);
                jPanel2.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ingresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private org.jdesktop.swingx.JXDatePicker date1;
    private org.jdesktop.swingx.JXDatePicker date2;
    private javax.swing.JLabel err;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel m;
    private javax.swing.JLabel ma;
    private javax.swing.JLabel mm;
    private javax.swing.JLabel mo;
    private javax.swing.JLabel mt;
    private javax.swing.JLabel o;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
