/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

import BD.DB;
import Entities.Fichero;
import Entities.Ticket;
import Entities.Vehiculo;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.joda.time.DateTime;
import org.joda.time.Period;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author luisf
 */
public class Salida extends javax.swing.JPanel {

    /**
     * Creates new form Salida
     */
    public Salida() {
        initComponents();
        Efectivo.setEnabled(false);
        tarjeta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fac = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tmp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Efectivo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        mat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ent = new javax.swing.JTextField();
        monto = new javax.swing.JFormattedTextField();
        tarjeta = new javax.swing.JButton();
        Err = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(700, 510));
        setMinimumSize(new java.awt.Dimension(700, 510));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(700, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "REGISTRAR SALIDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Salida");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 106, 33));

        try {
            fac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });
        jPanel2.add(fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Matrícula");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 106, 33));

        jTextField2.setEditable(false);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tiempo ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 106, 33));

        tmp.setEditable(false);
        tmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(tmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 20, 320));

        Efectivo.setText("Guarda Cambios");
        Efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectivoActionPerformed(evt);
            }
        });
        jPanel2.add(Efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Paga con");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Vuelto");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 80, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Número Fac.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 106, 33));

        jTextField4.setEditable(false);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 160, 30));

        mat.setEditable(false);
        mat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matActionPerformed(evt);
            }
        });
        jPanel2.add(mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 30));

        jButton2.setText("Registra Salida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Entrada");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 106, 33));

        ent.setEditable(false);
        ent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, 30));

        monto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jPanel2.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 160, 30));

        tarjeta.setText("Tarjeta");
        tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaActionPerformed(evt);
            }
        });
        jPanel2.add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, 30));

        Err.setForeground(new java.awt.Color(204, 0, 0));
        Err.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(Err, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 270, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 650, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Vehiculo v = BuscaFactura(fac.getText());
        if (v != null) {
            try {
                Fichero.eliminarObj(v);
                DB db = new DB();

                DateTime dt = new DateTime();
                v.setSalida(dt);
                Period p = new Period(v.getEntrada(), dt);

                int hours = p.getHours();
                int minutes = p.getMinutes();

                mat.setText(v.getMatricula());
                ent.setText(v.getEntrada().toString("HH:mm"));
                tmp.setText(p.getHours() + ":" + p.getMinutes());

                DateTimeFormatter fmt = DateTimeFormat.forPattern("HH:mm");
                jButton2.setText(fmt.print(dt));

                int d = p.getHours() * 60 + p.getMinutes() + p.getSeconds() / 60;
                double tt = (d == 0) ? 600 : d * 600;
                
                v.setTotal(tt);
                
                System.out.println(monto.getText().replace(",", ""));

                Ticket t = new Ticket("3654-4680083", new DateTime().toString("dd/MM/yyyy"), v.getEntrada().toString("HH:mm"), dt.toString("HH:mm"), String.valueOf(d), String.valueOf(v.getTotal()), "8395-0739");
                t.printSalida();
                t.printBytes();

                db.createRegistro(v);

                Efectivo.setEnabled(true);
                tarjeta.setEnabled(true);
                fac.setEditable(false);
                jButton2.setEnabled(false);
                Err.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.Err.setText("Num.factura incorrecta.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private Vehiculo BuscaFactura(String fac) {
        List<Vehiculo> lista = Fichero.buscaLista();
        Iterator<Vehiculo> itr = lista.iterator();

        while (itr.hasNext()) {
            Vehiculo v = (Vehiculo) itr.next();
            if (fac.equals(v.getNumFac())) {
                return v;
            }
        }
        return null;
    }


    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        System.out.println("enter");
    }//GEN-LAST:event_facActionPerformed

    private void matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matActionPerformed
        System.out.println("enter");
    }//GEN-LAST:event_matActionPerformed

    private void EfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectivoActionPerformed

    }//GEN-LAST:event_EfectivoActionPerformed

    private void tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Efectivo;
    private javax.swing.JLabel Err;
    private javax.swing.JTextField ent;
    private javax.swing.JFormattedTextField fac;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField mat;
    private javax.swing.JFormattedTextField monto;
    private javax.swing.JButton tarjeta;
    private javax.swing.JTextField tmp;
    // End of variables declaration//GEN-END:variables
}
