/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

import Entities.Fichero;
import Entities.Vehiculo;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author luisf
 */
public class TablaV extends javax.swing.JPanel {

    /**
     * Creates new form TablaV
     */
    public TablaV() {
        initComponents();
        datosTabla();
    }

    private void datosTabla() {
        ArrayList<Vehiculo> list = (ArrayList<Vehiculo>) Fichero.buscaLista();
        Iterator<Vehiculo> itr = list.iterator();
        int row = 0;
        int c = 0, m = 0, o = 0;

        while (itr.hasNext()) {
            Vehiculo aux = itr.next();
            this.jTable1.setValueAt(aux.getEntrada().toString("HH : mm"), row, 0);
            this.jTable1.setValueAt(aux.getTipo(), row, 1);
            switch (aux.getTipo()) {
                case "Automóvil Act": case "Automóvil":{
                    c++;
                    break;
                }
                case "Motocicleta Act": {
                    m++;
                    break;
                }
                case "Otro": {
                    o++;
                    break;
                }
            }
            this.jTable1.setValueAt(aux.getMatricula(), row, 2);
            this.jTable1.setValueAt(aux.getNumFac(), row++, 3);
        }
        this.o.setText(String.valueOf(o));
        this.c.setText(String.valueOf(c));
        this.m.setText(String.valueOf(m));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        co = new javax.swing.JLabel();
        cog = new javax.swing.JLabel();
        cop = new javax.swing.JLabel();
        cdg = new javax.swing.JLabel();
        cdp = new javax.swing.JLabel();
        cd = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(700, 510));
        setMinimumSize(new java.awt.Dimension(700, 510));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(700, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Entrada", "Tipo de Vehiculo", "Matricula", "Num Factura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 630, 290));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Datos de Vehiculos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 230, 20));

        jLabel2.setText("Otros:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        jLabel3.setText("Campos Ocupados:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel4.setText("Campos Disponibles:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jLabel5.setText("Carros:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel6.setText("Motocicletas:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        jLabel7.setText("Pequeños:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 60, -1));

        jLabel8.setText("Grandes:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 60, -1));

        jLabel9.setText("Grandes:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jLabel10.setText("Pequeños:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        co.setText("0");
        add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 30, -1));

        cog.setText("0");
        add(cog, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 30, -1));

        cop.setText("0");
        add(cop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 30, -1));

        cdg.setText("0");
        add(cdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 30, -1));

        cdp.setText("0");
        add(cdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 30, -1));

        cd.setText("0");
        add(cd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 30, -1));

        c.setText("0");
        add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 30, 10));

        m.setText("0");
        add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 30, 10));

        o.setText("0");
        add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 30, 10));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 10, 100));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 10, 100));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 10, 100));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c;
    private javax.swing.JLabel cd;
    private javax.swing.JLabel cdg;
    private javax.swing.JLabel cdp;
    private javax.swing.JLabel co;
    private javax.swing.JLabel cog;
    private javax.swing.JLabel cop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel m;
    private javax.swing.JLabel o;
    // End of variables declaration//GEN-END:variables
}
